pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// Live view of the current Omarchy theme.
//
// Two sources, both regenerated by `omarchy theme set`, so Duck restyles itself
// the moment the theme changes:
//
//   colors.toml  the raw palette
//   shell.toml   the surface tokens Omarchy styles its own bar and menus with
//                (control fills, borders, the type scale, spacing)
//
// Reading shell.toml rather than importing Omarchy's QML keeps Duck looking
// native without depending on the internal layout of its shell package.
//
// Geometry that belongs to the window manager — border width, corner radius,
// window gaps — is read from Hyprland itself so a bordered dock is
// indistinguishable from an ordinary window.
Singleton {
    id: root

    readonly property string stateDir: Quickshell.env("HOME") + "/.local/state/omarchy/current/theme"

    // --- palette (colors.toml) ---------------------------------------------

    property string mode: "dark"
    property color background: "#11111b"
    property color darkBackground: "#0d0d15"
    property color foreground: "#cdd6f4"
    property color accent: "#89b4fa"
    property color muted: "#6c7086"

    readonly property bool isDark: mode !== "light"

    // --- window manager geometry (Hyprland) --------------------------------

    property int borderWidth: 2
    property int cornerRadius: 0
    // Distance every ordinary window keeps from the screen edge.
    property int windowGap: 10
    // Compositor scale of the focused monitor; drives icon sizing.
    property real scale: 1.0

    // --- surface tokens (shell.toml) ---------------------------------------

    property var tokens: ({})

    // Control chrome, in the same four states Omarchy defines.
    function control(state) {
        const get = function (suffix, fallback) {
            const value = root.tokens["controls." + state + "-" + suffix];
            return value === undefined ? fallback : value;
        };

        return {
            "color": colorToken(get("color", root.foreground), root.foreground),
            "fillAlpha": Number(get("fill-alpha", 0.04)),
            "border": colorToken(get("border", root.foreground), root.foreground),
            "borderWidth": Number(get("border-width", 1)),
            "borderAlpha": Number(get("border-alpha", 0.4))
        };
    }

    function fill(state) {
        const spec = control(state);
        return Qt.rgba(spec.color.r, spec.color.g, spec.color.b, spec.fillAlpha);
    }

    function border(state) {
        const spec = control(state);
        return Qt.rgba(spec.border.r, spec.border.g, spec.border.b, spec.borderAlpha);
    }

    function borderWidthFor(state) {
        return control(state).borderWidth;
    }

    // shell.toml values may reference another token ("hyprland.active-border")
    // and borders may be full Hyprland gradients; take the first stop.
    function colorToken(value, fallback) {
        if (value === undefined || value === null) return fallback;

        let text = value.toString().trim();
        if (text.length === 0) return fallback;

        if (text.indexOf("hyprland.") === 0) {
            const target = root.tokens[text];
            if (target === undefined) return fallback;
            text = target.toString().trim();
        }

        const gradient = /(#[0-9a-fA-F]{6,8}|rgba?\([^)]*\))/.exec(text);
        if (gradient) text = gradient[1];

        try {
            return Qt.color(text);
        } catch (e) {
            return fallback;
        }
    }

    function token(path, fallback) {
        const value = root.tokens[path];
        return value === undefined ? fallback : value;
    }

    function surface(section, fallback) {
        return colorToken(root.tokens[section + ".background"], fallback);
    }

    function alphaSurface(section, fallback) {
        const base = surface(section, fallback);
        const alpha = Number(token(section + ".background-alpha", 1.0));
        return Qt.rgba(base.r, base.g, base.b, alpha);
    }

    // --- font ---------------------------------------------------------------
    //
    // `omarchy font set` writes the fontconfig alias, so the family is a
    // system-wide setting rather than a theme one. Rendering the concrete name
    // fc-match resolves (rather than the alias) means a font change repaints
    // Duck immediately instead of needing a restart.

    property string resolvedFontFamily: "monospace"

    // Omarchy lets summoned surfaces — menus, polkit, the clipboard — take a
    // different family via OMARCHY_MENU_FONT. The settings window is one of
    // those; the dock itself follows the bar.
    readonly property string fontFamily: resolvedFontFamily
    readonly property string menuFontFamily: {
        const override = Quickshell.env("OMARCHY_MENU_FONT");
        return (override && override.length > 0) ? override : resolvedFontFamily;
    }

    // --- type scale ---------------------------------------------------------

    readonly property real fontBase: Number(token("font.base-size", 12))

    readonly property int fontCaption: Math.round(Number(token("font.caption", fontBase * 0.833)))
    readonly property int fontBodySmall: Math.round(Number(token("font.body-small", fontBase * 0.917)))
    readonly property int fontBody: Math.round(Number(token("font.body", fontBase)))
    readonly property int fontSubtitle: Math.round(Number(token("font.subtitle", fontBase * 1.083)))
    readonly property int fontTitle: Math.round(Number(token("font.title", fontBase * 1.167)))
    readonly property int fontHeading: Math.round(Number(token("font.heading", fontBase * 1.333)))

    // --- spacing scale ------------------------------------------------------

    readonly property real spacingScale: Number(token("spacing.scale", 1.0))

    function space(value) {
        return Math.round(value * root.spacingScale);
    }

    readonly property int spacingXs: Math.round(Number(token("spacing.xs", 3)) * spacingScale)
    readonly property int spacingSm: Math.round(Number(token("spacing.sm", 4)) * spacingScale)
    readonly property int spacingMd: Math.round(Number(token("spacing.md", 6)) * spacingScale)
    readonly property int spacingLg: Math.round(Number(token("spacing.lg", 8)) * spacingScale)
    readonly property int spacingXl: Math.round(Number(token("spacing.xl", 10)) * spacingScale)
    readonly property int spacingXxl: Math.round(Number(token("spacing.xxl", 12)) * spacingScale)
    readonly property int spacingHuge: Math.round(Number(token("spacing.huge", 18)) * spacingScale)

    readonly property int controlHeight: Math.round(Number(token("spacing.control-height", 28)) * spacingScale)
    readonly property int rowPaddingX: Math.round(Number(token("spacing.row-padding-x", 12)) * spacingScale)
    readonly property int panelPadding: Math.round(Number(token("spacing.panel-padding", 18)) * spacingScale)

    // --- named surfaces -----------------------------------------------------

    readonly property color menuBackground: alphaSurface("menu", background)
    readonly property color menuText: colorToken(token("menu.text", foreground), foreground)
    readonly property color menuBorder: colorToken(token("menu.border", accent), accent)
    readonly property color menuSelected: Qt.rgba(
        colorToken(token("menu.selected-background", foreground), foreground).r,
        colorToken(token("menu.selected-background", foreground), foreground).g,
        colorToken(token("menu.selected-background", foreground), foreground).b,
        Number(token("menu.selected-background-alpha", 0.08)))

    readonly property color tooltipBackground: alphaSurface("tooltip", background)
    readonly property color tooltipText: colorToken(token("tooltip.text", foreground), foreground)
    readonly property color tooltipBorder: colorToken(token("tooltip.border", accent), accent)

    signal reloaded()

    // --- parsing ------------------------------------------------------------

    function parseColors(text) {
        const found = parseToml(text);

        if (found["mode"]) root.mode = found["mode"];
        if (found["background"]) root.background = found["background"];
        if (found["dark_background"]) root.darkBackground = found["dark_background"];
        if (found["foreground"]) root.foreground = found["foreground"];
        if (found["accent"]) root.accent = found["accent"];
        if (found["muted"]) root.muted = found["muted"];

        root.reloaded();
    }

    function parseShell(text) {
        root.tokens = parseToml(text, true);
        root.reloaded();
    }

    // Minimal TOML reader: these files are flat `key = value` under `[section]`
    // headers, with no arrays or nesting, so a real parser would be overkill.
    function parseToml(text, sectioned) {
        const found = {};
        const lines = text.split("\n");
        let section = "";

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i].trim();
            if (line.length === 0 || line.charAt(0) === "#") continue;

            if (line.charAt(0) === "[") {
                section = line.replace(/^\[|\]$/g, "").trim();
                continue;
            }

            const match = /^([A-Za-z_][A-Za-z0-9_-]*)\s*=\s*(.+)$/.exec(line);
            if (!match) continue;

            let value = match[2].trim();
            // Strip a trailing comment outside of quotes.
            if (value.charAt(0) !== '"') value = value.replace(/\s+#.*$/, "").trim();
            value = value.replace(/^"|"$/g, "");

            const key = sectioned && section.length > 0 ? section + "." + match[1] : match[1];
            found[key] = value;
        }

        return found;
    }

    FileView {
        path: root.stateDir + "/colors.toml"
        watchChanges: true
        preload: true
        printErrors: false

        onFileChanged: reload()
        onLoaded: root.parseColors(text())
    }

    FileView {
        path: root.stateDir + "/shell.toml"
        watchChanges: true
        preload: true
        printErrors: false

        onFileChanged: reload()
        onLoaded: root.parseShell(text())
    }

    // Hyprland owns border width, corner radius and window gaps. Reading them
    // back is what lets a bordered dock sit exactly where a window would.
    Process {
        id: hyprProbe

        running: true
        command: ["sh", "-c",
            "hyprctl getoption general:border_size -j; " +
            "hyprctl getoption decoration:rounding -j; " +
            "hyprctl getoption general:gaps_out -j; " +
            "hyprctl monitors -j"]

        stdout: StdioCollector {
            onStreamFinished: {
                // Four concatenated JSON documents; walk them by brace depth.
                const docs = [];
                let depth = 0;
                let start = -1;

                for (let i = 0; i < text.length; i++) {
                    const ch = text.charAt(i);
                    if (ch === "{" || ch === "[") {
                        if (depth === 0) start = i;
                        depth++;
                    } else if (ch === "}" || ch === "]") {
                        depth--;
                        if (depth === 0 && start >= 0) {
                            docs.push(text.substring(start, i + 1));
                            start = -1;
                        }
                    }
                }

                try {
                    if (docs.length > 0) {
                        const value = JSON.parse(docs[0]).int;
                        if (typeof value === "number" && value >= 0) root.borderWidth = value;
                    }
                    if (docs.length > 1) {
                        const value = JSON.parse(docs[1]).int;
                        if (typeof value === "number" && value >= 0) root.cornerRadius = value;
                    }
                    if (docs.length > 2) {
                        // "css": "10 10 10 10" (top right bottom left)
                        const css = JSON.parse(docs[2]).css;
                        if (css) {
                            const parts = css.toString().trim().split(/\s+/);
                            const bottom = parts.length >= 3 ? parseInt(parts[2], 10) : parseInt(parts[0], 10);
                            if (!isNaN(bottom)) root.windowGap = bottom;
                        }
                    }
                    if (docs.length > 3) {
                        const monitors = JSON.parse(docs[3]);
                        for (let i = 0; i < monitors.length; i++) {
                            if (monitors[i].focused && monitors[i].scale > 0) {
                                root.scale = monitors[i].scale;
                                break;
                            }
                        }
                    }
                } catch (e) {
                    // Cosmetic only — keep whatever defaults are in place.
                }
            }
        }
    }

    Process {
        id: fontProbe

        running: true
        command: ["fc-match", "-f", "%{family[0]}", "monospace"]

        stdout: StdioCollector {
            onStreamFinished: {
                const name = (text || "").toString().trim();
                if (name.length > 0) root.resolvedFontFamily = name;
            }
        }
    }

    // `omarchy font set` rewrites this file. Watching it means a font change
    // reaches Duck even though it is not a theme change.
    FileView {
        path: Quickshell.env("HOME") + "/.config/fontconfig/fonts.conf"
        watchChanges: true
        printErrors: false

        onFileChanged: root.refreshFont()
        onLoaded: root.refreshFont()
        onLoadFailed: root.refreshFont()
    }

    function refreshFont() {
        if (!fontProbe.running) fontProbe.running = true;
    }

    function refresh() {
        if (!hyprProbe.running) hyprProbe.running = true;
    }

    // A theme change rewrites Hyprland's config too, so re-probe with it.
    onReloaded: refresh()
}
